name = "mutsumi-proxy"
main = "worker.js"
compatibility_date = "2025-09-16"

[env.vars]
CUSTOM_DOMAIN = "mutsumi.sorali.org"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "mutsumi.sorali.org"

[env.production]
name = "mutsumi-proxy"

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""